# Generated by Django 4.0.6 on 2022-07-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=200)),
                ('status', models.BooleanField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
