# Generated by Django 4.0.6 on 2022-07-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
