# Generated by Django 4.0.6 on 2022-07-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
